export const categories = [
  { name: "Audio", slug: "audio", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800" },
  { name: "Wearables", slug: "wearables", image: "https://images.unsplash.com/photo-1544117519-31a4b719223d?w=800" },
  { name: "Workspace", slug: "workspace", image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800" },
  { name: "Carry", slug: "carry", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800" },
  { name: "Home", slug: "home", image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800" },
  { name: "Accessories", slug: "accessories", image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800" },
];

export const products = [
  {
    name: "Nova Wireless Headphones",
    category: "audio",
    price: 249,
    compareAtPrice: 299,
    stock: 34,
    rating: 4.7,
    reviewCount: 182,
    featured: true,
    tags: ["wireless", "noise-cancelling", "over-ear"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=1000",
    ],
    shortDescription: "Adaptive noise cancelling with 40-hour battery life.",
    description:
      "Nova pairs a warm, detailed sound signature with adaptive noise cancellation that adjusts in real time to your environment. The memory-foam ear cushions and titanium hinge are built for full-day wear, and a 40-hour battery means you rarely think about charging.",
  },
  {
    name: "Pulse Smart Watch",
    category: "wearables",
    price: 329,
    compareAtPrice: 379,
    stock: 21,
    rating: 4.5,
    reviewCount: 96,
    featured: true,
    tags: ["fitness", "health", "aluminum"],
    image: "https://images.unsplash.com/photo-1544117519-31a4b719223d?w=1000",
    images: ["https://images.unsplash.com/photo-1544117519-31a4b719223d?w=1000"],
    shortDescription: "Continuous health tracking in a lightweight aluminum case.",
    description:
      "Pulse tracks heart rate, sleep stages, and workouts with medical-grade sensors, wrapped in a case that's 30% lighter than the category average. The always-on display stays legible in direct sun, and the battery comfortably clears five days.",
  },
  {
    name: "Arc Mechanical Keyboard",
    category: "workspace",
    price: 179,
    stock: 40,
    rating: 4.8,
    reviewCount: 210,
    featured: true,
    tags: ["mechanical", "hot-swappable", "typing"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1000",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1000"],
    shortDescription: "Hot-swappable switches with a gasket-mounted deck.",
    description:
      "Arc's gasket-mounted plate gives every keystroke a cushioned, consistent bounce, while hot-swappable sockets let you change switches without a soldering iron. Machined from a single aluminum block, it's as much a desk object as it is a tool.",
  },
  {
    name: "Orbit Laptop Stand",
    category: "workspace",
    price: 69,
    stock: 58,
    rating: 4.4,
    reviewCount: 74,
    featured: false,
    tags: ["ergonomic", "aluminum", "portable"],
    image: "https://images.unsplash.com/photo-1611095973763-414019e72400?w=1000",
    images: ["https://images.unsplash.com/photo-1611095973763-414019e72400?w=1000"],
    shortDescription: "Folds flat for travel, opens to six ergonomic angles.",
    description:
      "Orbit raises your laptop to eye level in seconds and folds down to the thickness of a paperback for travel. Six angle settings and a ventilated deck keep your machine cool during long sessions.",
  },
  {
    name: "Mono Everyday Backpack",
    category: "carry",
    price: 159,
    compareAtPrice: 189,
    stock: 3,
    rating: 4.6,
    reviewCount: 141,
    featured: true,
    tags: ["water-resistant", "laptop-sleeve", "travel"],
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1000",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1000"],
    shortDescription: "A padded 16-inch sleeve inside a weatherproof shell.",
    description:
      "Mono is built from a single roll of recycled weatherproof canvas, with a padded compartment that fits a 16-inch laptop and a separate pocket for cables and chargers. The strap geometry is tuned to sit flat against your back on long commutes.",
  },
  {
    name: "Aura Desk Lamp",
    category: "home",
    price: 89,
    stock: 47,
    rating: 4.3,
    reviewCount: 58,
    featured: false,
    tags: ["led", "dimmable", "warm-light"],
    image: "https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?w=1000",
    images: ["https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?w=1000"],
    shortDescription: "Stepless dimming across a full warm-to-cool range.",
    description:
      "Aura's diffused LED array eliminates glare and hotspots on your desk, with stepless dimming and a color-temperature dial that moves smoothly from candle-warm to daylight-cool. The weighted base keeps it steady even on a crowded desk.",
  },
  {
    name: "Flow Wireless Mouse",
    category: "workspace",
    price: 59,
    stock: 0,
    rating: 4.5,
    reviewCount: 133,
    featured: false,
    tags: ["ergonomic", "silent-click", "multi-device"],
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=1000",
    images: ["https://images.unsplash.com/photo-1527814050087-3793815479db?w=1000"],
    shortDescription: "Silent clicks with instant three-device switching.",
    description:
      "Flow switches between three paired devices at the tap of a button, with a scroll wheel that free-spins for long documents and clicks for precise navigation. The silent switches make it comfortable for shared spaces.",
  },
  {
    name: "Echo Bluetooth Speaker",
    category: "audio",
    price: 129,
    stock: 26,
    rating: 4.6,
    reviewCount: 167,
    featured: true,
    tags: ["waterproof", "portable", "24-hour-battery"],
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=1000",
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=1000"],
    shortDescription: "IP67-rated with a 24-hour battery and rich low end.",
    description:
      "Echo pairs dual passive radiators with a sealed IP67 shell, so it survives rain, sand, and drops without losing the low end that makes it worth carrying outside. A single charge lasts a full weekend of casual listening.",
  },
  {
    name: "Vertex USB-C Hub",
    category: "accessories",
    price: 49,
    stock: 62,
    rating: 4.2,
    reviewCount: 89,
    featured: false,
    tags: ["usb-c", "hdmi", "compact"],
    image: "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=1000",
    images: ["https://images.unsplash.com/photo-1625948515291-69613efd103f?w=1000"],
    shortDescription: "7-in-1 connectivity in a pocketable aluminum shell.",
    description:
      "Vertex condenses HDMI, two USB-A ports, an SD reader, and 100W pass-through charging into a shell smaller than a car key. The aluminum body doubles as a heat sink, so it stays cool under sustained transfer.",
  },
  {
    name: "Lumen Smart Desk Light",
    category: "home",
    price: 99,
    compareAtPrice: 119,
    stock: 15,
    rating: 4.4,
    reviewCount: 47,
    featured: false,
    tags: ["app-controlled", "led", "scheduling"],
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1000",
    images: ["https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1000"],
    shortDescription: "App-scheduled lighting that follows your body clock.",
    description:
      "Lumen ramps brightness and color temperature on a schedule that mirrors natural daylight, dimming toward warm tones in the evening automatically. Manual control lives in a companion app with room-level presets.",
  },
  {
    name: "Halo Wireless Earbuds",
    category: "audio",
    price: 179,
    stock: 4,
    rating: 4.5,
    reviewCount: 121,
    featured: false,
    tags: ["earbuds", "anc", "wireless-charging"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1000",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1000"],
    shortDescription: "Compact ANC earbuds with a wireless-charging case.",
    description:
      "Halo fits three ear-tip sizes for a genuinely sealed fit, which is most of what makes its active noise cancellation effective. The case tops up wirelessly on any Qi pad and holds four additional charges.",
  },
  {
    name: "Strand Leather Wallet",
    category: "accessories",
    price: 79,
    stock: 33,
    rating: 4.7,
    reviewCount: 64,
    featured: false,
    tags: ["leather", "slim", "rfid-blocking"],
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=1000",
    images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=1000"],
    shortDescription: "Full-grain leather with an RFID-blocking liner.",
    description:
      "Strand is cut from a single piece of full-grain leather and hand-stitched with a hidden RFID-blocking liner, so the profile stays slim without giving up card security. It develops a deeper patina with every month of use.",
  },
  {
    name: "Ridge Travel Duffel",
    category: "carry",
    price: 189,
    stock: 18,
    rating: 4.6,
    reviewCount: 52,
    featured: false,
    tags: ["duffel", "water-resistant", "carry-on"],
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1000",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1000"],
    shortDescription: "Carry-on sized with a dedicated shoe compartment.",
    description:
      "Ridge is sized to clear carry-on limits on every major carrier, with a separate ventilated shoe compartment and a luggage-strap pass-through so it rides securely on a rolling case.",
  },
  {
    name: "Fold Portable Charger",
    category: "accessories",
    price: 45,
    stock: 71,
    rating: 4.1,
    reviewCount: 38,
    featured: false,
    tags: ["power-bank", "usb-c", "fast-charging"],
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=1000",
    images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=1000"],
    shortDescription: "10,000mAh with foldable prongs for direct wall use.",
    description:
      "Fold works as a standard power bank or plugs straight into the wall with its own foldout prongs, cutting one cable out of your bag entirely. 30W output charges most phones to 50% in under twenty minutes.",
  },
];
